collections:
- name: community.mongodb

roles:
- name: nginxinc.nginx
- name: geerlingguy.certbot
- name: geerlingguy.docker
- name: geerlingguy.pip
- name: googlecloudplatform.google_cloud_ops_agents
